### ISSUE TITLE
Sundry issues with latest Beta (Jan 2020)

### ISSUE THREAD

**Issue by KarellenX** [sualfred/script.metadata.editor#12]
Hi @sualfred Finally have time to play with the addon.

**-Global**
1. When entering a date (date added, last played) **01** and **02** for either day or month is not accepted. Occurs everywhere a date is used
2. Plot- impossible to accurately edit. I know we discussed previously

**-Movies**
Nil

**-TV Show**
1. Status- refuses an entry. Should be mapped back to C02 of the tvshow table
2. Play Count- does not accept an entry. There is no Play Count for tv shows. 

**-Music Artists**
1. Type- missing (Person / Group)
2. Gender- missing

**-Music Albums**
Nil

**-Music Songs**
1. Votes- Cannot update
2. There are a few fields missing - Genres, Comment and mood, but I don't know if these are used? 
@davetblake knows.

**-Music Videos**
1. Track - not sure what this is
2. Rating- not used
3. Userrating-  causes an error and exits the editor. The editor then becomes unusable. See log.

**-Movie Sets**
1. What are your thoughts of including Movie Sets in the Editor? Allow users to add the Overview.

Debug Log.... https://paste.kodi.tv/muwapenako.kodi
Errors at Line 8045 & 8171

**Comment by sualfred** [comment]
Thanks, have you tested on Leia or Matrix?

> When entering a date (date added, last played) 01 and 02 for either day or month is not accepted. Occurs everywhere a date is used

Kodi's keyboard is removing 0 but I add it after the value has been returned. Works on my end pretty well. Is it on Matrix?

> Plot- impossible to accurately edit. I know we discussed previously
Yeah, pita. I know

> Status- refuses an entry. Should be mapped back to C02 of the tvshow table
Works well on Leia. Matrix issue?

> Play Count- does not accept an entry. There is no Play Count for tv shows.
Removed it. Seems to be a virtual value if a show is marked as watched.

> Votes- Cannot update
Bug in the music JSON stuff. @DaveTBlake wanted to look at it
The other music stuff was removed because he recommended it. The music DB is like a house of cards it seems.

> Track - not sure what this is
Guess the same like a track on a CD, just for a concerte disc. It's there an can be edited.

> Rating- not used
Seems to be a bug in Kodi. Maybe related to the video database scheme? All other video items are storing their ratings in the <ratings> table now, except musicvideos. @enen92 can this be the case? Or is it a JSON bug in general? the types and methods file looks correct to me

> Userrating- causes an error and exits the editor. The editor then becomes unusable. See log.
Thanks, fixed.

> What are your thoughts of including Movie Sets in the Editor? Allow users to add the Overview.
Added the option to edit the label and overview. Works well. Also added a select dialog for movies to choose from existing sets in the editor

**Comment by KarellenX** [comment]
All tested on a nightly v18.6 

From log... **Starting Kodi (18.5 Git:20191217-429ddc9c14). Platform: Windows NT x86 64-bit**

Just tried again with the date issue. The 0 is being ignored.
If I want the date 01-02-2019 I end up with 10-2 instead of 01-02

Let me know if you need more info or testing.

**Comment by DaveTBlake** [comment]
> The music DB is like a house of cards it seems.

Feeling pretty insulted by that comment @sualfred especially if that is what you took away from our previous discussions! 

I gave some clear lists of what music data I think can be useful for users to edit manually here https://forum.kodi.tv/showthread.php?tid=349035&pid=2899286#pid2899286 
The JSON API allows for more song data to be set, but I think this is just asking users to get in a mess. Metadata from music files is primary, and that is where data changes for songs are best as subsequent changes made via API changes would be wiped by scanning. There is nothing "house of cards" about that, it is deliberate design.

I'm sure if @KarellenX had just seen **only** being able to set "playcount", "lastplayed", and "userrating" for songs he would have made sense of that limited choice of fields. 

But finally yes there are omissions/bugs in the JSON API implementation of `CAudioLibrary::SetSongDetails`, no surprise really since it isn't something that has ever been used (and like I have said of limited usefulness anyway). Setting "votes" is missing, and "mood" gets accidentally written to the wrong field.

**Comment by sualfred** [comment]
@DaveTBlake  Sorry, I just meant it's not save to offer the editing of our discussed fields for good reasons. I did not wanted to insult you. With a house of cards I just wanted to say it's too complex to offer all options. A wrong handling from my script or user interaction and it can cause a mess.

**Comment by sualfred** [comment]
> If I want the date 01-02-2019 I end up with 10-2 instead of 01-02
@KarellenX 
Tested it again with "1/2/2019" and it works.

Are you sure you are manually jumping to the next field (month) because Kodi doesn't do this on its own if you start with 0. It just ignores the number.

If yes, which date/region setting do you have?

**Comment by DaveTBlake** [comment]
Its OK @sualfred, we are still friends. Its just that the music db had bad press for years that it turned out it didn't deserve, so I jump on any dirty talk. Here it is the API which is the weak point.  

Allowing all data to be set is silly given that the music library is built from music file metadata, but the API was implemented without considering that. It blindly intended to edit all fields (but not add entries), but then some fields got left out by mistake or not added when changes were made.

The music db is robust enough that setting song details won't upset anything, but it is a futile thing for a user to do. Setting song playback history (playcount, lastplayed and userrating) does make sense, I would just offer those 3 fields for songs

**Comment by KarellenX** [comment]
>Are you sure you are manually jumping to the next field (month) because Kodi doesn't do this on its own if you start with 0. It just ignores the number.

No, I am not manually jumping to the next field.

If I enter 20-12-2019, then I am automatically jumped to the next field as I enter the numbers

If I enter 01-01-2019 then you say that I must manually jump to the next field to continue entering the date.

But then why can I enter 04-04-2019 and be automatically jumped to the next field?

If that is required, then that is inconsistent behaviour and will trip a lot of users up. Also realised it affects the **03** entry in addition to 01 & 02

So when entering 01, 02 and 03, you must manually jump

When entering 04, 05, 06, 07, 08, 09 you are automatically jumped to the next field

**Comment by sualfred** [comment]
Yes, weird behaviour of https://codedocs.xyz/xbmc/xbmc/group__python___dialog.html#ga061f23e5b01014ecb27ab00ddbed691e

There are only 2 other options:
a) Make the date complete editable as string "01/01/1960". But this allows users to enter garbage that needs to be validated afterwards
b) 1 integer dialog for day, 1 integer dialog for month, 1 integer dialog for year

**Comment by sualfred** [comment]
@KarellenX 
FYI
I've merged it to master and pushed a beta to my repo

**Comment by KarellenX** [comment]
ok, I'll make some time tomorrow

**Comment by sualfred** [comment]
Merged to Kodi repo today because it seems working as it should. I'll close this issue thread. If you find any new one just ping me in Slack or open a new one.
